// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Application
{
	public class DiceController
	{
		public DiceController ()
		{
		}

		public int value;

		private Die_d6 die;

		// Use this for initialization
		void Start () {
			//最初にランダムで回転させる
			transform.rotation = Random.rotation;
			die = gameObject.GetComponent<Die_d6>();
		}
		
		// Update is called once per frame
		void Update () {
			value = die.value;
			Debug.Log(value);
		}
	}
}

